config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "article#index"

  resources :article

  post 'comments', to: 'comments#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Article < ApplicationRecord
	has_many :paragraphs
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id           :integer          not null, primary key
#  comment      :string
#  paragraph_id :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Comment < ApplicationRecord
	belongs_to :paragraph
end

app/models/paragraph.rb
# == Schema Information
#
# Table name: paragraphs
#
#  id             :integer          not null, primary key
#  text           :text
#  article_id     :integer
#  foreign_key_id :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Paragraph < ApplicationRecord
	belongs_to :article
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true, with: :exception
  skip_before_action :verify_authenticity_token

end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
	def index
		#Return Article title, and first paragraph 
		params[:page] ||= 1
		params[:per_page] ||= 5
		@articles = Article.order(created_at: :desc).paginate(:page => params[:page], :per_page => params[:per_page])

	end

	def new
		#New Article view page
		
	end

	def create
		#Create new article with artciel params
		article = Article.create!(title: article_params[:title])
		params[:paragraph].each do |paragraph| 
			Paragraph.create(text: paragraph, article_id: article.id)
		end
		render json: {id: article.id}
	end

	def show
		@article = Article.find params[:id]	
		render json: {error: "not_found", error_description: "No record found with given id"}, status: :not_found if @article.blank?
	end

	private

	def article_params
		params.permit(:title, :paragraph)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def show
		#In case there are more than 5 comments and user want to load other comments
		respond_to do |format|
			@comments = Comment.where(paragraph_id: params[:paragraph_id])
		end
	end

	def create
		comment = Comment.create(comment_params)
		render json: {id: comment.id}
	end

	private

	def comment_params
		params.permit(:comment, :paragraph_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/article/index.html.erb
<% if @articles.present? %>
  <% @articles.each do |article| %>
    <h3><a href="<%= article_path(article.id) %>"><%= article.title %></a></h3>
    <p><%= article.paragraphs.first.try(:text) %></p>
  <% end %>
<% else %>
    No records found
<% end %>
<%= will_paginate @articles %>

app/views/article/new.html.erb
<form name="new-article-form" onSubmit="processArticle();return false;">
  <div class="form-group">
  	<label for="exampleTextarea">Title</label>
  	<input type="text" class="form-control" id="articleTitle" rows="10" name="title"></textarea>
  		<br/ ><br/ ><br/ >
  	<label for="exampleTextarea">Article Body</label>
    <textarea class="form-control" id="articleBody" rows="10" name="paragraph" ></textarea>
  </div>
  <br /><br /><br />
  <button type="submit" class="btn btn-primary">Submit</button>
	<button type="clear" class="btn btn-info" style="margin-left: 10%">Clear</button>
</form>

app/views/article/show.html.erb
<script>
	$(document).ready(function() {
    // document is loaded and DOM is ready
    var SideComments = require('side-comments');

  	// Then, create a new SideComments instance, passing in the wrapper element and the optional the current user and any existing comments.
  	var currentUser = {
	    id: 1,
    	avatarUrl: "/person.png",
    	name: "You"
  	};
  	var existingComments = [];

  	<%@article.paragraphs.try(:each) do |paragraph|%>
  		var hash = {};
  		hash["sectionId"] = "<%= paragraph.id %>";
  		var comments = [];
  		<%paragraph.comments.try(:each) do |comment|%>
  			var commentHash = {};
  			commentHash["authorAvatarUrl"] = "/person.png";
  			commentHash["authorName"] = "Person";
  			commentHash["comment"] = "<%= comment.comment%>";
  			comments.push(commentHash);
  		<%end%>
  		hash["comments"] = comments;
  		existingComments.push(hash);
  	<%end%>
	  sideComments = new SideComments('#commentable-area', currentUser, existingComments);

	  sideComments.on('commentPosted', function( comment ) {
	  console.log(comment);
	  //comment.id = parseInt(Math.random() * (100000 - 1) + 1);
	  comment.paragraph_id = comment.sectionId;
	  $.ajax({
        url: '/comments',
        type: 'POST',
        data: comment,
        success: function( savedComment ) {
            // Once the comment is saved, you can insert the comment into the comment stream with "insertComment(comment)".
            sideComments.insertComment(comment);
        },error: function(jqXHR, textStatus, errorThrown) {
       		alert("Error while processing comment")
       }
    });
	});
});

</script>

<div class="container">
	<h3><center><%= @article.title %></center></h3>
	<br/><br/>
	<div id="commentable-area">
		<%@article.paragraphs.try(:each) do |paragraph|%>
			<p data-section-id="<%= paragraph.id %>" class="commentable-section"> <%= paragraph.text %></p>
			<br/><br/>
	<%end%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogWithInlineComments</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/article">Blog with inline comments</a>
    </div>
      <ul class="nav navbar-nav navbar-right">
      <li><a href="/article/new"><span class="glyphicon glyphicon-pencil"></span> Create New</a></li>
    </ul>
  </div>
</nav>
  <div class="container">
    <div class="col-lg-6">
      <%= yield %>
    </div>
  </div>
</body>
</html>